
# ============================================================
# 🕘 APP CHẤM CÔNG - MỘT FILE DUY NHẤT
# ============================================================
# LƯU Ý:
# 1) App này dùng Supabase để dữ liệu KHÔNG mất khi Streamlit restart.
# 2) Trước lần chạy đầu tiên, cần tạo 2 bảng trong Supabase bằng SQL
#    ở cuối file (biến SUPABASE_SQL).
# 3) Streamlit Cloud Secrets:
#
# SUPABASE_URL = "https://xxxxxxxx.supabase.co"
# SUPABASE_SERVICE_ROLE_KEY = "eyJxxxxxxxx"
#
# Có thể dùng:
# pip install streamlit pandas openpyxl Pillow requests
# ============================================================

import streamlit as st
import requests
import hashlib
import hmac
import io
import calendar
from datetime import date, datetime
from pathlib import Path
import pandas as pd
from PIL import Image, ImageDraw, ImageFont

# ============================================================
# CẤU HÌNH
# ============================================================
st.set_page_config(
    page_title="Chấm công",
    page_icon="🕘",
    layout="wide",
    initial_sidebar_state="expanded",
)

DEFAULT_ADMIN = "admin"
DEFAULT_ADMIN_PASSWORD = "admin123"

# ============================================================
# CSS
# ============================================================
st.markdown("""
<style>
.main-title{font-size:30px;font-weight:800;margin-bottom:4px}
.sub-title{color:#6b7280;margin-bottom:20px}
.login-box{max-width:430px;margin:70px auto 0;padding:30px;border-radius:18px;
border:1px solid #e5e7eb;box-shadow:0 8px 30px rgba(0,0,0,.08);background:white}
div[data-testid="stMetric"]{border:1px solid #e5e7eb;padding:12px;border-radius:12px}
</style>
""", unsafe_allow_html=True)

# ============================================================
# SUPABASE
# ============================================================
def get_config():
    try:
        url = st.secrets["SUPABASE_URL"].rstrip("/")
        key = st.secrets["SUPABASE_SERVICE_ROLE_KEY"]
        return url, key
    except Exception:
        st.error("⚠️ Chưa cấu hình Supabase.")
        st.markdown("""
### Thêm vào Streamlit Cloud → Settings → Secrets

```toml
SUPABASE_URL = "https://YOUR-PROJECT.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "YOUR_SERVICE_ROLE_KEY"
```

Sau đó **Save → Reboot app**.
""")
        st.stop()


SUPABASE_URL, SUPABASE_KEY = get_config()

HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
}

REST = f"{SUPABASE_URL}/rest/v1"


def sb_request(method, table, params=None, json=None, headers_extra=None):
    """Gọi trực tiếp Supabase REST API."""
    headers = dict(HEADERS)

    if headers_extra:
        headers.update(headers_extra)

    response = requests.request(
        method,
        f"{REST}/{table}",
        headers=headers,
        params=params,
        json=json,
        timeout=30,
    )

    if not response.ok:
        raise RuntimeError(
            f"Supabase {response.status_code}: {response.text}"
        )

    if not response.text:
        return []

    try:
        return response.json()
    except Exception:
        return []


# ============================================================
# DATABASE
# ============================================================
def db_ready():
    try:
        sb_request(
            "GET",
            "users",
            params={
                "select": "id",
                "limit": "1",
            },
        )
        sb_request(
            "GET",
            "attendance",
            params={
                "select": "id",
                "limit": "1",
            },
        )
        return True
    except Exception:
        return False


def setup_database():
    """
    REST API của Supabase không cho tạo table trực tiếp.
    Hàm này chỉ kiểm tra database đã sẵn sàng chưa.
    """
    return db_ready()


def hash_password(password):
    return hashlib.sha256(
        password.encode("utf-8")
    ).hexdigest()


# ============================================================
# SQL - ĐƯỢC NHÉT NGAY TRONG FILE NÀY
# ============================================================
SUPABASE_SQL = r"""
create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    full_name text not null,
    role text not null default 'employee'
        check (role in ('employee', 'admin')),
    department text default '',
    position text default '',
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    username text not null,
    work_date date not null,
    check_in text default '',
    check_out text default '',
    status text not null default 'Đi làm',
    note text default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint attendance_user_date_unique
        unique (username, work_date)
);

create index if not exists idx_attendance_username
on public.attendance(username);

create index if not exists idx_attendance_work_date
on public.attendance(work_date);

create index if not exists idx_attendance_username_date
on public.attendance(username, work_date);

alter table public.users enable row level security;
alter table public.attendance enable row level security;
"""


# ============================================================
# USER
# ============================================================
def ensure_default_admin():
    try:
        existing = sb_request(
            "GET",
            "users",
            params={
                "select": "id,username",
                "username": f"eq.{DEFAULT_ADMIN}",
                "limit": "1",
            },
        )

        if existing:
            return

        sb_request(
            "POST",
            "users",
            json={
                "username": DEFAULT_ADMIN,
                "password_hash": hash_password(
                    DEFAULT_ADMIN_PASSWORD
                ),
                "full_name": "Quản trị viên",
                "role": "admin",
                "department": "Quản trị",
                "position": "Administrator",
                "active": True,
            },
        )

    except Exception as e:
        st.error("❌ Không thể khởi tạo tài khoản admin.")
        st.code(str(e))
        st.info(
            "Nếu báo lỗi relation 'users' does not exist, "
            "hãy chạy SUPABASE_SQL ở cuối file trong Supabase SQL Editor."
        )
        st.stop()


def authenticate(username, password):
    try:
        rows = sb_request(
            "GET",
            "users",
            params={
                "select": "*",
                "username": f"eq.{username.strip()}",
                "active": "eq.true",
                "limit": "1",
            },
        )

        if not rows:
            return None

        user = rows[0]

        if hmac.compare_digest(
            user["password_hash"],
            hash_password(password),
        ):
            return user

        return None

    except Exception:
        return None


def get_user(username):
    rows = sb_request(
        "GET",
        "users",
        params={
            "select": "*",
            "username": f"eq.{username}",
            "limit": "1",
        },
    )
    return rows[0] if rows else None


def get_users():
    rows = sb_request(
        "GET",
        "users",
        params={
            "select": (
                "id,username,full_name,role,department,"
                "position,active,created_at"
            ),
            "order": "full_name.asc",
        },
    )
    return pd.DataFrame(rows)


def create_user(username, password, full_name, role,
                department, position):
    try:
        sb_request(
            "POST",
            "users",
            json={
                "username": username.strip(),
                "password_hash": hash_password(password),
                "full_name": full_name.strip(),
                "role": role,
                "department": department.strip(),
                "position": position.strip(),
                "active": True,
            },
        )
        return True, "Tạo tài khoản thành công."
    except Exception as e:
        text = str(e)
        if "duplicate" in text.lower() or "unique" in text.lower():
            return False, "Tên đăng nhập đã tồn tại."
        return False, text


def update_user(user_id, full_name, department, position,
                role, active, password=None):
    payload = {
        "full_name": full_name.strip(),
        "department": department.strip(),
        "position": position.strip(),
        "role": role,
        "active": bool(active),
    }

    if password:
        payload["password_hash"] = hash_password(password)

    try:
        sb_request(
            "PATCH",
            "users",
            params={
                "id": f"eq.{user_id}",
            },
            json=payload,
        )
        return True, "Đã cập nhật."
    except Exception as e:
        return False, str(e)


# ============================================================
# ATTENDANCE
# ============================================================
def get_attendance(username, work_date):
    rows = sb_request(
        "GET",
        "attendance",
        params={
            "select": "*",
            "username": f"eq.{username}",
            "work_date": f"eq.{work_date}",
            "limit": "1",
        },
    )
    return rows[0] if rows else None


def upsert_attendance(username, work_date, check_in,
                      check_out, status, note):
    """
    QUAN TRỌNG:
    Một người + một ngày = một bản ghi.
    Chấm lại cùng ngày => UPDATE, không tạo bản ghi trùng.
    """
    payload = {
        "username": username,
        "work_date": work_date,
        "check_in": check_in,
        "check_out": check_out,
        "status": status,
        "note": note,
    }

    try:
        sb_request(
            "POST",
            "attendance",
            params={
                "on_conflict": "username,work_date",
            },
            json=payload,
            headers_extra={
                "Prefer": "resolution=merge-duplicates,return=representation"
            },
        )
        return True
    except Exception as e:
        st.error(f"❌ Không thể lưu chấm công: {e}")
        return False


def delete_attendance(username, work_date):
    try:
        sb_request(
            "DELETE",
            "attendance",
            params={
                "username": f"eq.{username}",
                "work_date": f"eq.{work_date}",
            },
        )
        return True
    except Exception as e:
        st.error(str(e))
        return False


def get_month_attendance(username, year, month):
    start = f"{year:04d}-{month:02d}-01"
    last_day = calendar.monthrange(year, month)[1]
    end = f"{year:04d}-{month:02d}-{last_day:02d}"

    rows = sb_request(
        "GET",
        "attendance",
        params={
            "select": "*",
            "username": f"eq.{username}",
            "work_date": f"gte.{start}",
            "work_date_end": f"lte.{end}",
            "order": "work_date.asc",
        },
    )

    # Một số Supabase/PostgREST phiên bản không thích tên
    # tham số work_date_end. Nếu query trên lỗi, dùng URL chuẩn bên dưới.
    return pd.DataFrame(rows)


def get_all_month_attendance(year, month, username=None):
    start = f"{year:04d}-{month:02d}-01"
    last_day = calendar.monthrange(year, month)[1]
    end = f"{year:04d}-{month:02d}-{last_day:02d}"

    params = {
        "select": "*",
        "work_date": f"gte.{start}",
        "order": "work_date.asc",
    }

    # REST không cho cùng một cột làm key 2 lần trong dict,
    # nên dùng khoảng bằng AND bằng cú pháp filter.
    params["and"] = f"(work_date.gte.{start},work_date.lte.{end})"

    if username:
        params["username"] = f"eq.{username}"

    rows = sb_request("GET", "attendance", params=params)
    df = pd.DataFrame(rows)

    if not df.empty:
        users = get_users()

        if not users.empty:
            info = users[
                ["username", "full_name", "department", "position"]
            ]
            df = df.merge(info, on="username", how="left")

    return df


def get_all_attendance_count():
    try:
        rows = sb_request(
            "GET",
            "attendance",
            params={
                "select": "id",
            },
        )
        return len(rows)
    except Exception:
        return 0


# ============================================================
# EXPORT EXCEL
# ============================================================
def make_excel(df):
    output = io.BytesIO()

    with pd.ExcelWriter(
        output,
        engine="openpyxl"
    ) as writer:
        df.to_excel(
            writer,
            index=False,
            sheet_name="BangCong"
        )

        ws = writer.book["BangCong"]

        for cells in ws.columns:
            max_length = 0
            letter = cells[0].column_letter

            for cell in cells:
                value = "" if cell.value is None else str(cell.value)
                max_length = max(
                    max_length,
                    len(value)
                )

            ws.column_dimensions[letter].width = min(
                max(max_length + 2, 12),
                35,
            )

    output.seek(0)
    return output.getvalue()


# ============================================================
# A4
# ============================================================
def get_font(size=24, bold=False):
    if bold:
        candidates = [
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf",
        ]
    else:
        candidates = [
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
        ]

    for path in candidates:
        if Path(path).exists():
            return ImageFont.truetype(path, size)

    return ImageFont.load_default()


def center_text(draw, box, text, font):
    x1, y1, x2, y2 = box

    bbox = draw.multiline_textbbox(
        (0, 0),
        text,
        font=font,
        spacing=2,
    )

    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]

    draw.multiline_text(
        (
            (x1 + x2 - tw) / 2,
            (y1 + y2 - th) / 2 - bbox[1],
        ),
        text,
        font=font,
        fill=(20,20,20),
        align="center",
        spacing=2,
    )


def create_month_sheet(username, year, month):
    user = get_user(username)

    if not user:
        return None

    W, H = 1754, 1240
    margin = 55

    img = Image.new(
        "RGB",
        (W, H),
        "white",
    )

    draw = ImageDraw.Draw(img)

    title_font = get_font(42, True)
    sub_font = get_font(25)
    head_font = get_font(22, True)
    cell_font = get_font(20)
    small_font = get_font(17)

    center_text(
        draw,
        (margin, 30, W-margin, 95),
        "BẢNG CHẤM CÔNG",
        title_font,
    )

    draw.text(
        (margin, 115),
        f"Họ và tên: {user['full_name']}",
        font=sub_font,
        fill=(20,20,20),
    )

    draw.text(
        (margin, 150),
        f"Mã đăng nhập: {user['username']}",
        font=sub_font,
        fill=(20,20,20),
    )

    draw.text(
        (700, 115),
        f"Bộ phận: {user.get('department') or '—'}",
        font=sub_font,
        fill=(20,20,20),
    )

    draw.text(
        (700, 150),
        f"Chức vụ: {user.get('position') or '—'}",
        font=sub_font,
        fill=(20,20,20),
    )

    center_text(
        draw,
        (margin, 185, W-margin, 230),
        f"THÁNG {month:02d}/{year}",
        head_font,
    )

    days = calendar.monthrange(year, month)[1]
    data = get_month_attendance(username, year, month)

    by_date = {}

    if not data.empty:
        by_date = {
            str(row["work_date"]): row.to_dict()
            for _, row in data.iterrows()
        }

    table_x = margin
    table_y = 255
    table_w = W - margin * 2
    table_h = 790

    label_w = 115
    day_w = (table_w - label_w) / days

    draw.rectangle(
        (
            table_x,
            table_y,
            table_x + table_w,
            table_y + table_h,
        ),
        outline=(0,0,0),
        width=2,
    )

    draw.line(
        (
            table_x + label_w,
            table_y,
            table_x + label_w,
            table_y + table_h,
        ),
        fill=(0,0,0),
        width=2,
    )

    center_text(
        draw,
        (
            table_x,
            table_y,
            table_x + label_w,
            table_y + 58,
        ),
        "NGÀY",
        head_font,
    )

    for d in range(1, days + 1):
        x1 = table_x + label_w + (d-1) * day_w
        x2 = table_x + label_w + d * day_w

        draw.line(
            (x2, table_y, x2, table_y + table_h),
            fill=(0,0,0),
            width=1,
        )

        dt = date(year, month, d)
        weekday = [
            "T2","T3","T4","T5","T6","T7","CN"
        ][dt.weekday()]

        center_text(
            draw,
            (x1, table_y, x2, table_y + 58),
            f"{d}\n{weekday}",
            small_font,
        )

    rows = [
        ("Trạng thái", "status"),
        ("Vào", "check_in"),
        ("Ra", "check_out"),
        ("Ghi chú", "note"),
    ]

    row_h = (table_h - 58) / len(rows)

    for i, (label, key) in enumerate(rows):
        y1 = table_y + 58 + i * row_h
        y2 = table_y + 58 + (i+1) * row_h

        draw.line(
            (table_x, y1, table_x + table_w, y1),
            fill=(0,0,0),
            width=1,
        )

        center_text(
            draw,
            (table_x, y1, table_x + label_w, y2),
            label,
            head_font,
        )

        for d in range(1, days + 1):
            x1 = table_x + label_w + (d-1) * day_w
            x2 = table_x + label_w + d * day_w

            work_date = (
                f"{year:04d}-{month:02d}-{d:02d}"
            )

            row = by_date.get(work_date)

            value = ""

            if row:
                value = str(row.get(key) or "")

            if key == "status":
                value = {
                    "Đi làm": "✓",
                    "Nghỉ phép": "P",
                    "Nghỉ": "N",
                    "Đi trễ": "T",
                    "Về sớm": "S",
                    "WFH": "WFH",
                }.get(value, value[:5])

            if len(value) > 10:
                value = value[:10]

            center_text(
                draw,
                (x1, y1, x2, y2),
                value,
                cell_font,
            )

    footer_y = table_y + table_h + 35

    statuses = (
        data["status"].tolist()
        if not data.empty
        else []
    )

    summary = (
        f"Đi làm: {statuses.count('Đi làm')}    "
        f"Nghỉ phép: {statuses.count('Nghỉ phép')}    "
        f"Nghỉ: {statuses.count('Nghỉ')}    "
        f"Đi trễ: {statuses.count('Đi trễ')}    "
        f"Về sớm: {statuses.count('Về sớm')}    "
        f"WFH: {statuses.count('WFH')}"
    )

    draw.text(
        (margin, footer_y),
        summary,
        font=sub_font,
        fill=(20,20,20),
    )

    draw.text(
        (margin, H - 65),
        "Xuất từ hệ thống chấm công • "
        + datetime.now().strftime("%d/%m/%Y %H:%M"),
        font=small_font,
        fill=(90,90,90),
    )

    output = io.BytesIO()

    img.save(
        output,
        format="PNG",
        dpi=(150,150),
    )

    output.seek(0)

    return output.getvalue()


# ============================================================
# LOGIN
# ============================================================
def login_page():
    st.markdown(
        '<div class="login-box">',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="main-title">🕘 Chấm công</div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="sub-title">Đăng nhập hệ thống</div>',
        unsafe_allow_html=True,
    )

    with st.form("login"):
        username = st.text_input("Tên đăng nhập")
        password = st.text_input(
            "Mật khẩu",
            type="password",
        )

        submit = st.form_submit_button(
            "🔐 Đăng nhập",
            use_container_width=True,
        )

        if submit:
            user = authenticate(
                username,
                password,
            )

            if user:
                st.session_state.logged_in = True
                st.session_state.username = user["username"]
                st.rerun()
            else:
                st.error(
                    "Tên đăng nhập hoặc mật khẩu không đúng."
                )

    st.caption(
        "Admin mặc định: admin / admin123"
    )

    st.markdown("</div>", unsafe_allow_html=True)


# ============================================================
# EMPLOYEE
# ============================================================
def employee_page(user):
    st.markdown(
        f'<div class="main-title">'
        f'Xin chào, {user["full_name"]} 👋'
        f'</div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="sub-title">'
        'Bảng chấm công cá nhân'
        '</div>',
        unsafe_allow_html=True,
    )

    today = date.today()
    today_str = today.isoformat()

    current = get_attendance(
        user["username"],
        today_str,
    )

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "Ngày hôm nay",
        today.strftime("%d/%m/%Y"),
    )

    c2.metric(
        "Giờ vào",
        (current or {}).get("check_in") or "—",
    )

    c3.metric(
        "Giờ ra",
        (current or {}).get("check_out") or "—",
    )

    st.divider()

    tab1, tab2, tab3 = st.tabs([
        "📝 Chấm công hôm nay",
        "📅 Bảng công tháng",
        "🖼️ Xuất A4",
    ])

    # --------------------------------------------------------
    # CHẤM CÔNG
    # --------------------------------------------------------
    with tab1:
        with st.form("attendance_today"):
            c1, c2 = st.columns(2)

            with c1:
                default_in = datetime.now().time()

                if current and current.get("check_in"):
                    try:
                        default_in = datetime.strptime(
                            current["check_in"],
                            "%H:%M",
                        ).time()
                    except Exception:
                        pass

                check_in = st.time_input(
                    "Giờ vào",
                    value=default_in,
                )

            with c2:
                default_out = datetime.now().time()

                if current and current.get("check_out"):
                    try:
                        default_out = datetime.strptime(
                            current["check_out"],
                            "%H:%M",
                        ).time()
                    except Exception:
                        pass

                check_out = st.time_input(
                    "Giờ ra",
                    value=default_out,
                )

            statuses = [
                "Đi làm",
                "Nghỉ phép",
                "Nghỉ",
                "Đi trễ",
                "Về sớm",
                "WFH",
            ]

            status = st.selectbox(
                "Trạng thái",
                statuses,
                index=(
                    statuses.index(current["status"])
                    if current
                    and current.get("status") in statuses
                    else 0
                ),
            )

            note = st.text_input(
                "Ghi chú",
                value=(current or {}).get("note", ""),
            )

            save = st.form_submit_button(
                "💾 LƯU CHẤM CÔNG",
                use_container_width=True,
            )

            if save:
                ok = upsert_attendance(
                    user["username"],
                    today_str,
                    check_in.strftime("%H:%M"),
                    check_out.strftime("%H:%M"),
                    status,
                    note,
                )

                if ok:
                    st.success(
                        "✅ Đã lưu thành công."
                    )
                    st.rerun()

    # --------------------------------------------------------
    # BẢNG CÔNG
    # --------------------------------------------------------
    with tab2:
        year = st.number_input(
            "Năm",
            min_value=2020,
            max_value=2100,
            value=today.year,
            key="emp_year",
        )

        month = st.selectbox(
            "Tháng",
            range(1, 13),
            index=today.month - 1,
            key="emp_month",
        )

        df = get_month_attendance(
            user["username"],
            int(year),
            int(month),
        )

        rows = []

        days = calendar.monthrange(
            int(year),
            int(month),
        )[1]

        for d in range(1, days + 1):
            dt = date(
                int(year),
                int(month),
                d,
            )

            found = (
                df[df["work_date"] == dt.isoformat()]
                if not df.empty
                else pd.DataFrame()
            )

            if not found.empty:
                r = found.iloc[0]

                rows.append({
                    "Ngày": dt.strftime("%d/%m/%Y"),
                    "Thứ": [
                        "T2","T3","T4","T5",
                        "T6","T7","CN"
                    ][dt.weekday()],
                    "Vào": r.get("check_in", ""),
                    "Ra": r.get("check_out", ""),
                    "Trạng thái": r.get("status", ""),
                    "Ghi chú": r.get("note", ""),
                })
            else:
                rows.append({
                    "Ngày": dt.strftime("%d/%m/%Y"),
                    "Thứ": [
                        "T2","T3","T4","T5",
                        "T6","T7","CN"
                    ][dt.weekday()],
                    "Vào": "",
                    "Ra": "",
                    "Trạng thái": "",
                    "Ghi chú": "",
                })

        st.dataframe(
            pd.DataFrame(rows),
            use_container_width=True,
            hide_index=True,
        )

    # --------------------------------------------------------
    # A4
    # --------------------------------------------------------
    with tab3:
        year = st.number_input(
            "Năm xuất",
            min_value=2020,
            max_value=2100,
            value=today.year,
            key="emp_export_year",
        )

        month = st.selectbox(
            "Tháng xuất",
            range(1, 13),
            index=today.month - 1,
            key="emp_export_month",
        )

        if st.button(
            "🖼️ Tạo bảng công A4",
            use_container_width=True,
        ):
            st.session_state.emp_png = create_month_sheet(
                user["username"],
                int(year),
                int(month),
            )

            st.session_state.emp_png_name = (
                f"Bang_cong_{user['username']}_"
                f"{int(month):02d}_{int(year)}.png"
            )

        if st.session_state.get("emp_png"):
            st.image(
                st.session_state.emp_png,
                use_container_width=True,
            )

            st.download_button(
                "⬇️ Tải ảnh A4",
                st.session_state.emp_png,
                file_name=st.session_state.emp_png_name,
                mime="image/png",
                use_container_width=True,
            )


# ============================================================
# ADMIN
# ============================================================
def admin_page(user):
    st.markdown(
        '<div class="main-title">'
        '🛠️ TRUNG TÂM QUẢN TRỊ'
        '</div>',
        unsafe_allow_html=True,
    )

    users_df = get_users()

    total_users = len(users_df)

    active_users = (
        int(users_df["active"].sum())
        if not users_df.empty
        else 0
    )

    records = get_all_attendance_count()

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "Tổng tài khoản",
        total_users,
    )

    c2.metric(
        "Đang hoạt động",
        active_users,
    )

    c3.metric(
        "Lượt chấm công",
        records,
    )

    st.divider()

    tab1, tab2, tab3, tab4 = st.tabs([
        "👥 Nhân viên",
        "📝 Chấm công",
        "📊 Bảng công",
        "🖼️ Xuất A4",
    ])

    # ========================================================
    # USERS
    # ========================================================
    with tab1:
        st.subheader("Danh sách tài khoản")

        if not users_df.empty:
            show = users_df.copy()

            show["active"] = show["active"].map({
                True: "Đang hoạt động",
                False: "Đã khóa",
            })

            st.dataframe(
                show.rename(columns={
                    "username": "Tên đăng nhập",
                    "full_name": "Họ tên",
                    "role": "Vai trò",
                    "department": "Bộ phận",
                    "position": "Chức vụ",
                    "active": "Trạng thái",
                    "created_at": "Ngày tạo",
                }),
                use_container_width=True,
                hide_index=True,
            )

        with st.expander("➕ Tạo tài khoản"):
            with st.form("new_user"):
                c1, c2 = st.columns(2)

                with c1:
                    username = st.text_input(
                        "Tên đăng nhập *"
                    )

                    full_name = st.text_input(
                        "Họ và tên *"
                    )

                    password = st.text_input(
                        "Mật khẩu *",
                        type="password",
                    )

                with c2:
                    role = st.selectbox(
                        "Vai trò",
                        ["employee", "admin"],
                    )

                    department = st.text_input(
                        "Bộ phận"
                    )

                    position = st.text_input(
                        "Chức vụ"
                    )

                submit = st.form_submit_button(
                    "Tạo tài khoản",
                    use_container_width=True,
                )

                if submit:
                    if not username.strip() or not full_name.strip() or not password:
                        st.error(
                            "Vui lòng nhập đủ thông tin."
                        )
                    else:
                        ok, msg = create_user(
                            username,
                            password,
                            full_name,
                            role,
                            department,
                            position,
                        )

                        if ok:
                            st.success(msg)
                            st.rerun()
                        else:
                            st.error(msg)

        with st.expander("✏️ Sửa tài khoản"):
            if users_df.empty:
                st.info("Chưa có tài khoản.")
            else:
                selected_username = st.selectbox(
                    "Chọn tài khoản",
                    users_df["username"].tolist(),
                    key="edit_user_select",
                )

                selected = get_user(
                    selected_username
                )

                with st.form("edit_user"):
                    c1, c2 = st.columns(2)

                    with c1:
                        full_name = st.text_input(
                            "Họ tên",
                            selected["full_name"],
                        )

                        department = st.text_input(
                            "Bộ phận",
                            selected.get("department") or "",
                        )

                        position = st.text_input(
                            "Chức vụ",
                            selected.get("position") or "",
                        )

                    with c2:
                        role_options = [
                            "employee",
                            "admin",
                        ]

                        role = st.selectbox(
                            "Vai trò",
                            role_options,
                            index=(
                                role_options.index(
                                    selected["role"]
                                )
                                if selected["role"] in role_options
                                else 0
                            ),
                        )

                        active = st.checkbox(
                            "Đang hoạt động",
                            bool(selected["active"]),
                        )

                        password = st.text_input(
                            "Mật khẩu mới",
                            type="password",
                        )

                    submit = st.form_submit_button(
                        "💾 Lưu",
                        use_container_width=True,
                    )

                    if submit:
                        if (
                            selected["username"]
                            == user["username"]
                            and not active
                        ):
                            st.error(
                                "Không thể tự khóa tài khoản đang đăng nhập."
                            )
                        else:
                            ok, msg = update_user(
                                selected["id"],
                                full_name,
                                department,
                                position,
                                role,
                                active,
                                password or None,
                            )

                            if ok:
                                st.success(msg)
                                st.rerun()
                            else:
                                st.error(msg)

    # ========================================================
    # ADMIN ATTENDANCE
    # ========================================================
    with tab2:
        employees = users_df[
            users_df["role"] == "employee"
        ].copy()

        if employees.empty:
            st.info("Chưa có nhân viên.")
        else:
            options = {
                f"{r['full_name']} ({r['username']})":
                    r["username"]
                for _, r in employees.iterrows()
            }

            label = st.selectbox(
                "Nhân viên",
                list(options.keys()),
            )

            selected_username = options[label]

            work_date = st.date_input(
                "Ngày",
                date.today(),
            )

            existing = get_attendance(
                selected_username,
                work_date.isoformat(),
            )

            with st.form("admin_attendance"):
                c1, c2 = st.columns(2)

                with c1:
                    check_in = st.text_input(
                        "Giờ vào",
                        (existing or {}).get(
                            "check_in",
                            "",
                        ),
                    )

                    statuses = [
                        "Đi làm",
                        "Nghỉ phép",
                        "Nghỉ",
                        "Đi trễ",
                        "Về sớm",
                        "WFH",
                    ]

                    status = st.selectbox(
                        "Trạng thái",
                        statuses,
                        index=(
                            statuses.index(
                                existing["status"]
                            )
                            if existing
                            and existing.get("status")
                            in statuses
                            else 0
                        ),
                    )

                with c2:
                    check_out = st.text_input(
                        "Giờ ra",
                        (existing or {}).get(
                            "check_out",
                            "",
                        ),
                    )

                    note = st.text_input(
                        "Ghi chú",
                        (existing or {}).get(
                            "note",
                            "",
                        ),
                    )

                a, b = st.columns(2)

                save = a.form_submit_button(
                    "💾 Lưu",
                    use_container_width=True,
                )

                remove = b.form_submit_button(
                    "🗑️ Xóa",
                    use_container_width=True,
                )

                if save:
                    if upsert_attendance(
                        selected_username,
                        work_date.isoformat(),
                        check_in.strip(),
                        check_out.strip(),
                        status,
                        note.strip(),
                    ):
                        st.success("Đã lưu.")
                        st.rerun()

                if remove:
                    if delete_attendance(
                        selected_username,
                        work_date.isoformat(),
                    ):
                        st.success("Đã xóa.")
                        st.rerun()

    # ========================================================
    # TABLE
    # ========================================================
    with tab3:
        c1, c2 = st.columns(2)

        with c1:
            year = st.number_input(
                "Năm",
                2020,
                2100,
                date.today().year,
                key="admin_year",
            )

        with c2:
            month = st.selectbox(
                "Tháng",
                range(1,13),
                date.today().month - 1,
                key="admin_month",
            )

        employee_choices = (
            ["Tất cả"]
            + users_df.loc[
                users_df["role"] == "employee",
                "username"
            ].tolist()
        )

        employee = st.selectbox(
            "Nhân viên",
            employee_choices,
            key="admin_employee",
        )

        selected_username = (
            None
            if employee == "Tất cả"
            else employee
        )

        df = get_all_month_attendance(
            int(year),
            int(month),
            selected_username,
        )

        if df.empty:
            st.info(
                "Chưa có dữ liệu trong tháng này."
            )
        else:
            show = df.rename(columns={
                "username": "Tài khoản",
                "full_name": "Họ tên",
                "department": "Bộ phận",
                "position": "Chức vụ",
                "work_date": "Ngày",
                "check_in": "Giờ vào",
                "check_out": "Giờ ra",
                "status": "Trạng thái",
                "note": "Ghi chú",
            })

            st.dataframe(
                show,
                use_container_width=True,
                hide_index=True,
            )

            st.download_button(
                "⬇️ Xuất Excel",
                make_excel(show),
                file_name=(
                    f"Bang_cong_{int(month):02d}_"
                    f"{int(year)}.xlsx"
                ),
                mime=(
                    "application/vnd.openxmlformats-officedocument."
                    "spreadsheetml.sheet"
                ),
                use_container_width=True,
            )

    # ========================================================
    # A4
    # ========================================================
    with tab4:
        employees = users_df[
            users_df["role"] == "employee"
        ].copy()

        if employees.empty:
            st.info("Chưa có nhân viên.")
        else:
            options = {
                f"{r['full_name']} ({r['username']})":
                    r["username"]
                for _, r in employees.iterrows()
            }

            label = st.selectbox(
                "Nhân viên",
                list(options.keys()),
                key="a4_employee",
            )

            selected_username = options[label]

            c1, c2 = st.columns(2)

            with c1:
                year = st.number_input(
                    "Năm",
                    2020,
                    2100,
                    date.today().year,
                    key="a4_year",
                )

            with c2:
                month = st.selectbox(
                    "Tháng",
                    range(1,13),
                    date.today().month - 1,
                    key="a4_month",
                )

            if st.button(
                "🖼️ Tạo ảnh bảng công A4",
                use_container_width=True,
            ):
                st.session_state.a4_png = (
                    create_month_sheet(
                        selected_username,
                        int(year),
                        int(month),
                    )
                )

                st.session_state.a4_name = (
                    f"Bang_cong_{selected_username}_"
                    f"{int(month):02d}_{int(year)}.png"
                )

            if st.session_state.get("a4_png"):
                st.image(
                    st.session_state.a4_png,
                    use_container_width=True,
                )

                st.download_button(
                    "⬇️ Tải ảnh A4",
                    st.session_state.a4_png,
                    file_name=st.session_state.a4_name,
                    mime="image/png",
                    use_container_width=True,
                )


# ============================================================
# MAIN
# ============================================================
if not setup_database():
    st.error(
        "❌ Database Supabase chưa được tạo."
    )

    st.markdown(
        "### Làm đúng 1 lần:"
    )

    st.markdown(
        "1. Mở **Supabase → SQL Editor**  \n"
        "2. New query  \n"
        "3. Copy toàn bộ SQL bên dưới  \n"
        "4. Bấm **Run**  \n"
        "5. Quay lại Streamlit và **Reboot app**."
    )

    st.code(
        SUPABASE_SQL,
        language="sql",
    )

    st.stop()


ensure_default_admin()

if "logged_in" not in st.session_state:
    st.session_state.logged_in = False

if not st.session_state.logged_in:
    login_page()
    st.stop()

username = st.session_state.get("username")
user = get_user(username)

if not user or not user["active"]:
    st.session_state.clear()
    st.rerun()

with st.sidebar:
    st.markdown("## 🕘 CHẤM CÔNG")
    st.caption(
        f"Xin chào **{user['full_name']}**"
    )
    st.caption(
        f"Tài khoản: `{user['username']}`"
    )
    st.caption(
        f"Vai trò: `{user['role']}`"
    )

    st.divider()

    if st.button(
        "🚪 Đăng xuất",
        use_container_width=True,
    ):
        st.session_state.clear()
        st.rerun()

if user["role"] == "admin":
    admin_page(user)
else:
    employee_page(user)
